# Generated by Django 3.1.6 on 2022-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_account_can_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
    ]
