# Generated by Django 3.1.6 on 2022-01-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20220109_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='can_post',
        ),
    ]
